# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(
    task: ":Empty:test",
    gradle_path: "../gradlew"
    )
  end

  lane :testDebug do
    gradle(
    task: ":Empty:testDebugUnitTest",
    gradle_path: "../gradlew"
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Publish the result apk into appcenter"
  lane :appCentr do
    gradle(
        tasks: ["clean", ":Empty:assembleRelease"],
        gradle_path: "../gradlew"
         )
    appcenter_upload(
      api_token: ENV["APP_CENTER_API_TOKEN"],
      owner_name: "Coronel-Org",
      owner_type: "user", # Default is user - set to organization for appcenter organizations
      app_name: "Empty-Screen-App",
      file: "build/outputs/apk/release/Empty-release-unsigned.apk",
      notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
    )
  end
end
